### ISSUE TITLE
Cannot read property 'displayName' of undefined at V2Agent.processRequest

### ISSUE THREAD

**Issue by JaTvoiRabotnik** [dialogflow/dialogflow-fulfillment-nodejs#150]
I have set up small talk. There doesn't seem to be an obvious way to prevent it from triggering the fulfillment engine (which I have as a webhook). 

The problem is that this is passed on as matching an Intent, but with the intent name empty. So when V2Agent.processRequest tries to get the property displayName from this.agent.request_.body.queryResult.intent, we get the error:
```
   "TypeError: Cannot read property 'displayName' of undefined
    at V2Agent.processRequest_ (/srv/node_modules/dialogflow-fulfillment/src/v2-agent.js:62:69)
    at new WebhookClient (/srv/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:229:17)"   
```

**Comment by JaTvoiRabotnik** [comment]
I am getting around this problem for now by capturing the request before the web hook is initialised and checking whether `queryResult.action.includes('smalltalk')`. If it does, I just terminate the fulfillment abruptly.

**Comment by matthewayne** [comment]
You can disable fulfillment for small talk with the domains fulfillment option: ![](https://i.imgur.com/ZUeDMTw.png)
