### ISSUE TITLE
response failed when more than one agent.add is fired

### ISSUE THREAD

**Issue by tschnoelzer** [dialogflow/dialogflow-fulfillment-nodejs#18]
hi team,

when I use fulfillment version  "dialogflow-fulfillment": "^0.3.0-beta.2" I have trouble with the request. I get log 

```
Error: No responses defined for platform: undefined
    at WebhookClient.send_ (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:428:13)
    at promise.then (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:246:38)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

when calling e.g.

```
  function fallback(agent) {
    agent.add(`I didn't understand YO`);
    agent.add(`I'm sorry, can you try again?`);
  }
```

it is running perfect with only one entry like:

```
  function fallback(agent) {
    agent.add(`I didn't understand YO`);
   // agent.add(`I'm sorry, can you try again?`);
  }
```

using node v9.10.1

**Comment by tschnoelzer** [comment]
It was a matter of wrong node version. downgraded to node@6 and it works!
