### ISSUE TITLE
Leave response empty so Dialogflow's response is applied

### ISSUE THREAD

**Issue by stasusov** [dialogflow/dialogflow-fulfillment-nodejs#180]
Earlier (in the v0.4) of the lib we had a possibility not to add any response in the fulfillment. Therefore, if no `agent.add()` was called, Dialogflow applied the response which is set up in the Dialogflow itself. I recently updated the dependency to the v0.6 and it is throwing an exception if no response is added:

```
(node:243) UnhandledPromiseRejectionWarning: Error: No responses defined for platform: null
at V2Agent.sendResponses_ (/app/node_modules/dialogflow-fulfillment/src/v2-agent.js:243:13)
at WebhookClient.send_ (/app/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:505:17)
at promise.then (/app/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:321:38)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

Platform is not important in this case, I have the same behaviour for both Dialogflow testing console and Facebook.

How can I achieve the same behaviour I had in the v0.4?

**Comment by jquinter** [comment]
> This will be fixed in the next release (v0.6.2)

When is that fix going to be released? Latest is still 0.6.1 with the bug.

**Comment by apolineaire** [comment]
Any way or work-around to achieve this painlessly ? Sometimes DF's response is sent, sometimes nothing is sent.

**Comment by reyerm** [comment]
Any updated on this please?
May be wrong, but i _think_ this fork fixes it
https://www.npmjs.com/package/dialogflow-fulfillment-improved

**Comment by apolineaire** [comment]
Just in case it might help someone, I found a **dirty** workaround : 

1. Configure your intents so they all send requests to your webhook endpoint (in my case we _needed_ to do it to log every conversation on our bot).
2. In your controller, do something like "if there is no handler set for this intent in my backend, send back the default answer", as the default answer written in Dialogflow's interface is sent along in the request. You can set the flag "no handler needed in the backend" by using Dialogflow's actions.

**Comment by tylercaceres** [comment]
Hello everyone. Any update on this by any chance?
cc: @matthewayne 🙏

**Comment by Useems** [comment]
Since the library is abandoned, I found a temporary workaround:

```js
agent.response_.sendStatus(200);
agent.response_.json = () => {};
agent.add('end');
```
