### ISSUE TITLE
Issue when mixing with fulfillment messages from console

### ISSUE THREAD

**Issue by exs6350** [dialogflow/dialogflow-fulfillment-nodejs#192]
Upgraded to 0.6.1 and ran into a bug when mixing fulfillment messages coming from console and from our own fulfillment function. For some messages we keep the response in the dialogflow console and for others we fulfill them from our function. An example of this is when the default fallback intent is triggered we have the responses in the console but our webhook call will fail with:
 
Error: No responses defined for platform: null
    at V2Agent.sendResponses_ (/srv/node_modules/dialogflow-fulfillment/src/v2-agent.js:243:13)
    at WebhookClient.send_ (/srv/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:505:17)
    at promise.then (/srv/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:303:38)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

Even though the webhook call fails, dialogflow will still show the correct response. Got around the error from being thrown by just adding an empty message `agent.add("")` when we want to use responses from console.

**Comment by arnm** [comment]
related #220
