### ISSUE TITLE
dialogflow

### ISSUE THREAD

**Issue by kumaresan93** [dialogflow/dialogflow-fulfillment-nodejs#201]
TypeError: BrowseCarouselItem is not a constructor
    at Destination (/user_code/index.js:42:9)
    at WebhookClient.handleRequest (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:303:44)
    at exports.dialogflowFirebaseFulfillment.functions.https.onRequest (/user_code/index.js:81:9)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/providers/https.js:57:9)
    at /var/tmp/worker/worker.js:724:7
    at /var/tmp/worker/worker.js:707:11
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by sarahdwyer** [comment]
Can you post the code you have that produced this error?

**Comment by Vadorequest** [comment]
I don't get why this kind of issue isn't closed right away, what a waste of time to deal with.
People who think they have to be helped even without explaining anything, open source is not developer support dammit.

**Comment by maganap** [comment]
@Vadorequest Lol, and I don't get why @sarahdwyer even bothered to ask for code...

@kumaresan93 , `BrowseCarouselItem` is from [`actions-on-google`](https://github.com/actions-on-google/actions-on-google-nodejs), not from [`dialogflow-fulfillment`](https://github.com/dialogflow/dialogflow-fulfillment-nodejs).

Take a look at the source code here:
https://github.com/dialogflow/dialogflow-fulfillment-nodejs/tree/master/src/rich-responses
There's only generic Card objects you can use.
