### ISSUE TITLE
this.agent.response_.json is not a function

### ISSUE THREAD

**Issue by naseemali925** [dialogflow/dialogflow-fulfillment-nodejs#245]
Hi, 
I am trying to use this library with `fastify`
I am passig the `request`  `response` to the WebhookClient
But when the endpoint is hit, it gives the following erro
```
(node:9984) UnhandledPromiseRejectionWarning: TypeError: this.agent.response_.json is not a function
    at V2Agent.sendResponses_ (G:\Nodes\sjpl-graph-ql\node_modules\dialogflow-fulfillment\src\v2-agent.js:255:26)
    at WebhookClient.send_ (G:\Nodes\sjpl-graph-ql\node_modules\dialogflow-fulfillment\src\dialogflow-fulfillment.js:505:17)
    at promise.then (G:\Nodes\sjpl-graph-ql\node_modules\dialogflow-fulfillment\src\dialogflow-fulfillment.js:316:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
**Please let me know if this library can be used with fastify?**

**Comment by naseemali925** [comment]
See #246
